name: Build & Test Pintos
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-filesys-check:
    runs-on: ubuntu-latest
    container:
      image: thierrysans/pintos
    steps:
    - name: Build and test Filesys
      uses: actions/checkout@v2
    - run: cd src/filesys && make clean && make check
