name: Build & Test Pintos
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-threads:
    runs-on: ubuntu-latest
    container:
      image: thierrysans/pintos
    steps:
    - name: Build and test threads
      uses: actions/checkout@v2
    - run: bash test_pintos.sh
  
  # TODO: Add more jobs here for user programs, virtual memory, file system
